### PR TITLE
Using go modules (Go 1.11+)

### PR DESCRIPTION
**Pull request by im-kulikov**
### Proposed changes in this pull request
Using Go modules (Go 1.11+)

`Dep` was an experiment and at the moment, it is over.
Starting with Go 1.11, the built-in solution`go mod` is used

### Type (put an `x` where ever applicable)
- [ ] Bug fix: Link to the issue
- [x] Feature (Non-breaking change)
- [ ] Feature (Breaking change)
- [ ] Documentation Improvement

### Checklist
Please put an `x` against the checkboxes. Write a small comment explaining if its `N/A` (not applicable)

- [x] Read the [CONTRIBUTION guidelines](https://github.com/CityOfZion/neo-storm/blob/master/CONTRIBUTING.md).
- [x] All the tests are passing after the introduction of new changes.
- [ ] Added tests respective to the part of code I have written.
- [ ] Added proper documentation where ever applicable (in code and README.md).

### Extra information
Any extra information related to this pull request.

### CODE REVIEW

**Comment by anthdm** [comment]
This will be merged with master in the next release candidate. Thank you for your contribution.

**Comment by anthdm** [comment]
@im-kulikov Do we not need to remove the old gopkg files?

**Comment by im-kulikov** [comment]
`go mod` used only for Go 1.11+

for back capability I guess we must keep this files

**Comment by anthdm** [comment]
@im-kulikov That makes sense.

**Comment by im-kulikov** [comment]
@anthdm when 1.12+ will be released, we can remove go-dep files

**Pull request merged**
